"""Generate docs/construction-spec-register.md from the construction manifest.

Itemizes every parameter Almond's construction knowledge layer uses and
resolves each system's bci_ref section numbers against the page-indexed
table of contents (docs/reference/bci_toc.txt) of the source volume:

    Francis D.K. Ching, Building Construction Illustrated, 4th ed.
    (Wiley, 2014)

Run from the repo root:  python tools/build_spec_register.py
The register is generated - edit the manifest (or this script), not the
output file.
"""
from __future__ import annotations

import json
import re
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "Constructionfiles" / "manifest.json"
TOC = ROOT / "docs" / "reference" / "bci_toc.txt"
OUT = ROOT / "docs" / "construction-spec-register.md"

# Reference tables live in the appendix; their sections are fixed.
REFERENCE_SOURCES = {
    "live_loads_kpa": ("A.06 Building Live Loads", 446),
    "material_densities_kg_m3": ("A.07 Weights of Materials", 447),
    "egress_rules": ("A.10-A.13 Means of Egress / Fire-Rated Construction "
                     "(+ 9.03-9.05 stair design)", 450),
}


def parse_toc() -> dict[str, tuple[str, int]]:
    """Map section number ('4.26') -> (title, pdf page)."""
    sections: dict[str, tuple[str, int]] = {}
    pattern = re.compile(r"^\s*(\d{1,2}\.\d{2}|A\.\d{2})\s+(.*?)\s+->\s+pdf page (\d+)")
    for line in TOC.read_text(encoding="utf-8").splitlines():
        match = pattern.match(line.replace("\t", " "))
        if match:
            num, title, page = match.groups()
            sections[num] = (title.strip(), int(page))
    return sections


def section_sort_key(num: str) -> tuple:
    chapter, item = num.split(".")
    return (99, int(item)) if chapter == "A" else (int(chapter), int(item))


def resolve_ref(ref: str, sections: dict) -> list[tuple[str, str, int]]:
    """'4.26-4.32' -> the TOC sections that fall inside the range."""
    ref = ref.strip()
    if "-" in ref:
        start, end = [r.strip() for r in ref.split("-", 1)]
        if "." not in end:  # '4.26-32' shorthand
            end = start.split(".")[0] + "." + end
    else:
        start = end = ref
    lo, hi = section_sort_key(start), section_sort_key(end)
    hits = [(num, t, p) for num, (t, p) in sections.items()
            if lo <= section_sort_key(num) <= hi]
    return sorted(hits, key=lambda h: section_sort_key(h[0]))


def spacing_text(spacing) -> str:
    if not spacing:
        return "-"
    parts = [f"element: {spacing.get('element', '?')}"]
    if "options" in spacing:
        parts.append("options " + "/".join(f"{v*1000:.0f} mm" for v in spacing["options"]))
    if "typical" in spacing:
        parts.append(f"typical {spacing['typical']*1000:.0f} mm")
    if "min" in spacing or "max" in spacing:
        lo = spacing.get("min"); hi = spacing.get("max")
        rng = (f"{lo*1000:.0f}" if lo is not None else "?") + "-" + \
              (f"{hi*1000:.0f} mm" if hi is not None else "?")
        parts.append(rng)
    if "note" in spacing:
        parts.append(spacing["note"])
    return "; ".join(parts)


def main() -> None:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    sections = parse_toc()
    lines: list[str] = []
    w = lines.append

    w("# Construction spec register")
    w("")
    w("Itemized source register for every parameter in "
      "`Constructionfiles/manifest.json`. Each value is traced to its section "
      "in **Francis D.K. Ching, *Building Construction Illustrated*, 4th ed. "
      "(Wiley, 2014)** ('BCI'); page numbers are PDF pages of that volume, "
      "matching [reference/bci_toc.txt](reference/bci_toc.txt). Values BCI "
      "defers to the building code are labeled *IBC-typical* and must be "
      "verified against the governing code.")
    w("")
    w(f"Generated {date.today().isoformat()} by `tools/build_spec_register.py` "
      "- regenerate after editing the manifest; do not edit this file by hand.")
    w("")
    w("All rules of thumb are preliminary-sizing guidance for design "
      "plausibility, not a substitute for engineering analysis.")
    w("")

    # ── systems ──────────────────────────────────────────────────────────
    by_category: dict[str, list[dict]] = {}
    for system in manifest["systems"]:
        by_category.setdefault(system["category"], []).append(system)

    w("## Construction systems")
    w("")
    for category in ("floor", "wall", "roof", "foundation", "longspan"):
        systems = by_category.get(category)
        if not systems:
            continue
        w(f"### {category.capitalize()} systems")
        w("")
        for s in systems:
            w(f"#### `{s['system_id']}` - {s['name']}")
            w("")
            refs = []
            for ref in s.get("bci_ref", []):
                hits = resolve_ref(ref, sections)
                if hits:
                    refs.append(f"BCI {ref}: " + "; ".join(
                        f"{num} *{title}* (p. {page})" for num, title, page in hits))
                else:
                    refs.append(f"BCI {ref}")
            w("**Source:** " + " | ".join(refs))
            w("")
            w("| Parameter | Value | Basis |")
            w("| --- | --- | --- |")
            axis = "unsupported height" if s.get("span_axis") == "vertical" else "span"
            lo, hi = s["span_range_m"]
            if hi > 0:
                w(f"| {axis} range | {lo:g}-{hi:g} m | BCI {', '.join(s.get('bci_ref', []))} |")
            w(f"| structural material (Karamba) | {s['structural_material']} | "
              f"validate_structure vocabulary |")
            if s.get("structure_types"):
                w(f"| analysis templates | {', '.join(s['structure_types'])} | "
                  f"validate_structure structure_type |")
            if s.get("render_material_ids"):
                w(f"| typical finishes (Materialfiles) | "
                  f"{', '.join(s['render_material_ids'])} | assign_material ids |")
            for rule in s.get("depth_rules", []):
                ratio = rule.get("span_ratio", 0)
                value = f"depth = span/{ratio}" if ratio else rule.get("note", "-")
                note = rule.get("note", "")
                w(f"| {rule['element']} sizing | {value} | {note} |")
            sp = spacing_text(s.get("typical_spacing_m"))
            if sp != "-":
                w(f"| spacing | {sp} | BCI {', '.join(s.get('bci_ref', []))} |")
            w("")
            if s.get("elements"):
                w("**Elements:**")
                w("")
                for element in s["elements"]:
                    w(f"- `{element['role']}` - {element['note']}")
                w("")
            if s.get("construction_notes"):
                w("**Construction notes:**")
                w("")
                for note in s["construction_notes"]:
                    w(f"- {note}")
                w("")

    # ── reference tables ─────────────────────────────────────────────────
    reference = manifest.get("reference", {})
    w("## Reference tables")
    w("")

    title, page = REFERENCE_SOURCES["live_loads_kpa"]
    w(f"### Occupancy live loads - BCI {title} (p. {page})")
    w("")
    w("Converted from psf at 1 psf = 47.88 Pa. Minimum uniformly distributed "
      "design loads; verify against the governing code.")
    w("")
    w("| Occupancy | Live load (kPa) |")
    w("| --- | --- |")
    for key, value in reference.get("live_loads_kpa", {}).items():
        w(f"| {key.replace('_', ' ')} | {value:g} |")
    w("")

    title, page = REFERENCE_SOURCES["material_densities_kg_m3"]
    w(f"### Material densities - BCI {title} (p. {page})")
    w("")
    w("Converted from pcf at 1 pcf = 16.018 kg/m3.")
    w("")
    w("| Material | Density (kg/m3) |")
    w("| --- | --- |")
    for key, value in reference.get("material_densities_kg_m3", {}).items():
        w(f"| {key.replace('_', ' ')} | {value:g} |")
    w("")

    egress = reference.get("egress_rules", {})
    if egress:
        title, page = REFERENCE_SOURCES["egress_rules"]
        w(f"### Egress and fire-rating rules - BCI {title} (p. {page}+)")
        w("")
        w(f"> {egress.get('source_note', '')}")
        w("")
        w("| Rule | Value | Basis |")
        w("| --- | --- | --- |")
        for key, value in egress.get("occupant_load_m2_per_person", {}).items():
            w(f"| occupant load: {key.replace('_', ' ')} | {value:g} m2/person | IBC-typical |")
        for tier in egress.get("exits_required_by_occupant_load", []):
            cap = tier["max_occupants"]
            label = f"<= {cap} occupants" if cap else "above the previous tier"
            note = f" ({tier['note']})" if tier.get("note") else ""
            w(f"| exits required: {label} | {tier['exits']}{note} | BCI A.10 framework, IBC-typical tiers |")
        for key, value in egress.get("exit_separation_fraction_of_diagonal", {}).items():
            w(f"| exit separation ({key}) | >= diagonal x {value:g} | IBC-typical |")
        for key, value in egress.get("max_travel_distance_m", {}).items():
            w(f"| max travel distance: {key.replace('_', ' ')} | {value:g} m | IBC-typical |")
        for key, value in egress.get("max_dead_end_corridor_m", {}).items():
            w(f"| max dead-end corridor ({key.replace('_', ' ')}) | {value:g} m | IBC-typical |")
        for key, value in egress.get("egress_width_mm_per_occupant", {}).items():
            w(f"| egress width: {key.replace('_', ' ')} | {value:g} mm/occupant | IBC-typical |")
        for key, value in egress.get("min_widths_mm", {}).items():
            w(f"| min width: {key.replace('_', ' ')} | {value:g} mm | BCI 9.04 |")
        for key, value in egress.get("stair_rules_mm", {}).items():
            unit = "" if isinstance(value, str) else " mm"
            w(f"| stair: {key.replace('_', ' ')} | {value}{unit} | BCI 9.03-9.05 |")
        fire = egress.get("fire_resistance", {})
        for wall_kind in ("solid_reinforced_concrete_wall_mm", "solid_brick_wall_mm", "cmu_wall_mm"):
            for rating, thickness in fire.get(wall_kind, {}).items():
                w(f"| fire rating: {wall_kind.replace('_mm','').replace('_',' ')}, "
                  f"{rating.replace('_',' ')} | {thickness} mm | BCI A.12 |")
        w("")
        if fire.get("shaft_enclosure_note"):
            w(f"> {fire['shaft_enclosure_note']}")
        w("")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(lines)} lines, "
          f"{len(manifest['systems'])} systems, {len(sections)} TOC sections)")


if __name__ == "__main__":
    main()
